### ISSUE TITLE
Tags that mirror the FDS release version tags

### ISSUE THREAD

**Issue by TristanHehnen** [firemodels/out#469]
Hello everybody!

To my understanding these validation cases are run before the release of a new stable and then the results are uploaded here. 
I would like to ask if for this validation repository the tags could be mirrored/matched to the tags from the FDS stable tags in the main repo. This would make it a bit easier to connect the created output to the FDS release.

Best,
Tristan

**Comment by mcgratta** [comment]
The validation cases take about a month to run. During that time, normal development and bug fixing continues. It would be difficult to halt everything for a month while the cases are running.
